### ISSUE TITLE
X-XSRF-TOKEN header is not working

### ISSUE THREAD

**Issue by thetutlage** [adonisjs/adonis-shield#8]
When a client library makes an ajax request with `X-XSRF-TOKEN` header by reading the value from `XSRF-TOKEN` cookie, it just fails.

The library in use is axios

**Comment by thetutlage** [comment]
Seems to be working fine for me here https://github.com/thetutlage/adonis-shield-8

**Comment by vaggelis2018** [comment]
@thetutlage in monday i ll send you my own repo from my workplace to check the issue better. Thanks for our time.

**Comment by thetutlage** [comment]
Suggest you to reproduce the issue within the same repo I shared, since it’s hard for me to setup your entire project and then hunt down the issue

**Comment by jake-a-wood** [comment]
I'm having this same issue. I ran your code @thetutlage and it worked just fine. However, my use of adonis is based off of this scaffold https://github.com/nuxt-community/adonuxt-template. 

I went ahead and attempted the same type of axios post like you did but I get the "EBADCSRFTOKEN: Invalid CSRF token" error. 

From what I can tell as I dig into this, it has to do with an error in the way the token is verified or encrypted. The values seem to line up otherwise. 

I'll update with more info as I find it.

**Comment by jake-a-wood** [comment]
Went ahead and created a fresh installation of https://github.com/nuxt-community/adonuxt-template and followed your example as closely as I could @thetutlage. 

https://github.com/jake-a-wood/adonis-shield-w-nuxt-failed-csrf

The only changes I made were in these files:
- https://github.com/jake-a-wood/adonis-shield-w-nuxt-failed-csrf/blob/master/resources/pages/index.vue
- https://github.com/jake-a-wood/adonis-shield-w-nuxt-failed-csrf/blob/master/start/routes.js

The .env file I'm using is mostly default except the port is changed to 3001.

**Comment by vaggelis2018** [comment]
@jake-a-wood i have the same built like you and i think that this may have to do from the ssr. I tried to pass the same token to both server side and client side but with no effect. Have you found any solution?

**Comment by jake-a-wood** [comment]
@vaggelis2018 I have not. I've only found the following details:
- Multiple new tokens are being generated per page load.
- The token being sent to the page matches one of these (usually the first one).
- The comparison of the encrypted token being sent back up doesn't end up resolving to the expected output on the server, causing CSRF token check to fail.

I don't yet know the ins and outs of the nuxt render method enough to understand why there are all those token regenerations per page load, but I'm guessing that's why the tokens never match up when the next POST is sent up.

As an aside, I also some how got it to work under unusual circumstances. In VS Code, I ran the debugger and set a breakpoint on the route I'm attempting to POST to. Somehow in the mix of using the debugger, restarting and such, the calls just started working. I'm not sure why this would be the case and when I go incognito or to safari it's still broken; so I don't feel like this is a true solution to anything, but it might give some hint to what's going on.

I hope this is useful info.

**Comment by vaggelis2018** [comment]
Thanks. As i see you are at the same place with me. You are right that the tokens to the client and server side are the same. But for some reason adonis keep rejects them.

**Comment by thetutlage** [comment]
So here are couple of things. In short I don't think using CSRF protection with SSR will take you far enough, why?

1. CSRF token is generated by Adonis and after first page load, all subsequent page loads will be done by Nuxt and hence once user session will expire, the CSRF protection will start failing. 

2. Enough though your Vue and AdonisJs codebase is same, you should not couple both of them. Think of Adonis as the API only server and build it in a way, if you ever plan to host Nuxt app somewhere else, it should work fine.

## Okay why it doesn't work

AdonisJs ends the response as soon as your controller method is executed. It is called `implicitEnd`. 
In your case Nuxt wants to write and end the response, so you have to turn off the `implicitEnd` mode.

```js
response.implicitEnd = false
```

Now when you do this, session fails to write, since it doesn't know when response is going to end. So you have to commit the session by hand.

```js
await session.commit()
```

Finally, replace the `render` method of Nuxt controller with the following code and everything will work fine. I will share a PR with them too.

```js
  async render ({ request: { request: req }, response, session }) {
    response.implicitEnd = false
    await session.commit()
    await new Promise((resolve, reject) => {
      this.nuxt.render(req, response.response, promise => {
        promise.then(resolve).catch(reject)
      })
    })
  }
```

**Comment by thetutlage** [comment]
Closing this issue and let's wait to get the related PR merge inside AdoNuxt template

**Comment by jake-a-wood** [comment]
I very much appreciate your insight on this! I was indeed having a hard time assessing the proper relationship between adonis and nuxt.

Thanks!

**Comment by chris-schmitz** [comment]
:clap: :clap: thanks for taking the time to explain that out @thetutlage.

**Comment by vaggelis2018** [comment]
@thetutlage Thank you very much for your time and your effort for the issue.

**Comment by nbolender** [comment]
@jake-a-wood Did you get this working with the adonuxt template? I've integrated the latest from the template but am still getting the token mismatch, in addition to a bunch of tokens being generated on each page load as assets are loading in.

**Comment by jake-a-wood** [comment]
@nbolender I'm having it working in the environment I was first having the issue with. I haven't gone back and checked the original  example though. When I get time, I'll go ahead and look at the example.

**Comment by DJafari** [comment]
@thetutlage your solution work for requests on client

in my project, i must fill store in `nuxtServerInit` and always return csrf error
