### ISSUE TITLE
[RFC] Optional Session

### ISSUE THREAD

**Issue by RomainLanz** [adonisjs/adonis-shield#9]
Hey everyone! :wave:

This package currently depends on the Adonis Session Provider. Adding this package make Adonis create session for every user reaching your website.

This can be an issue when you want to have a stateless API but need the shield package to enable some security like the CSRF Protection.

**Why the CSRF Protection would be needed for an API?**  

When doing an API, the most common way to authenticate a user is to use JWT.
Therefore, your client need to use it and send it for each request.

1. You are using `localStorage`/`sessionStorage` and use the HTTP header `Authorization: Bearer <token>`.
2. You are using an HTTP Only cookie.

Those way to handle a JWT aren’t secured. The first one makes you vulnerable to XSS attacks. The second one makes you vulnerable to CSRF attacks.

You cannot avoid being vulnerable to XSS attacks but you can avoid it for CSRF attacks.

It can be achieved by two ways:

1. You are sending a CSRF Token inside another cookie (not HTTP Only). Your backend will then verify the origin of the request and the token with the value stored in session.
2. You are using the Double Submit Cookie pattern.

The main issue with the first solution is that you need your backend to use session. That is not what we want.

**Which changes are needed inside the Shield package?**

Since we do need the CSRF token generated by the shield package what could we do?  
  
1. Create another package/middleware that handle only CSRF and doesn't use session.
2. Patch Adonis Shield to only use session when the session provider is registered.

**Comment by Frondor** [comment]
Such a delicate topic, I'll drop my 50ç here. In my opinion, it looks more like an authentication driver for a session package than a problem to be solved by adonis-shield.
:bulb:  Or make adonis-shield to register the driver for you? :thinking: 

I'm fan of splitting the JWT and use one part as the CSRF token. I came with this idea after reading [Getting Token Authentication Right in a Stateless Single Page Application](https://medium.com/lightrail/getting-token-authentication-right-in-a-stateless-single-page-application-57d0c6474e3).
Take it as a sub-RFC of this one :D 

## [Store splitted JWT for CSRF protection](https://security.stackexchange.com/questions/179487)

I wanted to find a more secure solution for authenticating stateless javascript apps, so created that question few months ago, after reading a lot about the topic.

Basically I proposed to take advantage of the JWT nature (`{header}.{payload}.{signature}`), and split it into different blocks that you may store differently in the front-end, but put back together in the backend for each authenticated request.
Upon a successful login request, the `{signature}` is supposed to be returned in a `httpOnly & secure` cookie (thus mitigating XSS in one go), and then the rest of that token (`{header}.{payload}`) in the request body, for the client app to store it in html5 storage (mitigating CSRF attacks, since the full token can not be obtained now) and set the Authorization header with it on every authenticated request.

Now the server expects the request to contain a Authorization: Bearer {header}.{payload} header, along with the httpOnly cookie carrying the JWT's signature, which appended to said header, should form the whole JWT.

Quick example: 
```js
const token = req.headers.Authorization.split('Bearer ')[1].concat('.' + req.cookies.jwt_signature)
JWT.verify(token)
```

This way I refrain from computing an extra CSRF token and use something like a "re-built" version of the jwt.

More on this:

- [What if JWT is stolen?](https://stackoverflow.com/questions/34259248/what-if-jwt-is-stolen/48647036#48647036)
- https://github.com/sahat/satellizer/issues/833#issuecomment-343803762

**Comment by RomainLanz** [comment]
This method seems very interesting. It avoids the cost of creating a CSRF Token but keeps the API secured.

Thinking about the implementation, I don't know if we should add it to the core or create an additional package that extends `@adonis/auth`. What are you thougths @thetutlage ?

**Comment by thetutlage** [comment]
Thanks for taking out time to share your views on this. Breaking these comments into following bullet points.

- **Storage: Localstorage**: If website is vunerable with XSS, then someone can steal the JWT token.
- **Storage: Cookies**: The classic problem of cookies, where important actions must be verified using CSRF tokens.

Now, also see, Why do people use JWT over classic session auth

- Mobile apps
- API exposed publicly and want to others to connect to it.
- Stateless client apps, where tight coupling with the server is not possible.

In all the scanerios where JWT is used kills the point of using CSRF token. The token has to be generated on the server and must be delivered to the client. Now if delivering of token happens over normal REST endpoint, then anyone can get it.

Localstorage is bad for sure, but if your website is vunerable with XSS, then what are the other options?

## Store splitted JWT token
I like the idea but have certain questions around it.

1. First the same `Authorization` header cannot be used. Since it simply breaks the predictability and server doesn't know if the value is the complete token or parts of it. 
2. `signature` must be sent in an HTTP only cookie and rest over HTTP header. 
    
Now again if your website is vunerable with `XSS` attack, then using Javascript, I can drop a link on your webpage (assuming a financial site). On clicking that link, a request on the same server is made to transfer all money to a different account.

**Comment by Frondor** [comment]
> First the same `Authorization` header cannot be used. Since it simply breaks the predictability and server doesn't know if the value is the complete token or parts of it. Also not feasible for mobile apps

Well, it may break the predictability if you're not expecting it that way. That's why a dedicated session/auth driver might be needed for this .

> Also not feasible for mobile apps

That's right, but you can make the driver smart enough for that specific case. Like using the `deviceId` to issue the token, and validate it if present in the JWT payload.

> Now again if your website is vunerable with XSS attack, then using Javascript, I can drop a link on your webpage (assuming a financial site). On clicking that link, a request on the same server is made to transfer all money to a different account. **This will work, since I can run Javascript on your webpage and the signature cookie will be forwarded to the server anyways**

That's where a good [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) comes to practice. If I white-list my javascript sources, you shouldn't be able to inject anything and act on behalf of an user with js.

The approach is very opinionated, but to me, it looks like the way to go if you're looking for RESTful APIs and pure javascript clients.
Now, if you're building an API for a native mobile app, then you can handle the authentication normally, since you don't need to worry about these attacks.
Anyway, it's not that common to use the same authentication system for both, browser and mobile apps.
